# Generated by Django 5.0.4 on 2024-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_time_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
