# Generated by Django 5.0.4 on 2024-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала работы'),
        ),
    ]
